export const routes = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  VFTPHONENUMBERSCREEN: 'VFTPHONENUMBERSCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  SEND_EMAIL: 'SEND_EMAIL',
  VFT_PHONENUMBER_SCREEN: 'VFT_PHONENUMBER_SCREEN',
  PRODUCT_SCREEN: 'PRODUCT_SCREEN',
  INFO_SCREEN: 'INFO_SCREEN',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  ENTER_PHONE_NUMBER_SCREEN: 'ENTER_PHONE_NUMBER_SCREEN',
  STATS_SCREEN: 'STATS_SCREEN',
  COURSESCREEN: 'COURSESCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  DETAILS_COURSE_SCREEN: 'DETAILS_COURSE_SCREEN',
  COURCE_SCREEN: 'COURCE_SCREEN',
  COURSE_LIST_SCREEN: 'COURSE_LIST_SCREEN',
  PRODUCT_LIST_SCREEN: 'PRODUCT_LIST_SCREEN',

  //Tabs
  TAB_DETAILS: 'TAB_DETAILS',
  TAB_LESSSON: 'TAB_LESSSON',
};
