export const routes = {
  // BOTTOM
  BOTTOM_TAB: 'BOTTOM_TAB',
  BOTTOM_TAB_PRODUCT: 'BOTTOM_TAB_PRODUCT',
  HOME_SCREEN: 'HOME_SCREEN',
  INFO_SCREEN: 'INFO_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  STATS_SCREEN: 'STATS_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  SUPPLEMENTS_SCREEN: 'Supple',
  EQUIPMENT_SCREEN: 'Equip',
  CLOTHING_SCREEN: 'Clothing & Accessories',

  // AUTHENTICATION
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  ONBOARD_SCREEN: 'ONBOARD_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  VFT_PHONE_NUMBER_SCREEN: 'VFT_PHONE_NUMBER_SCREEN',
  SEND_EMAIL_SCREEN: 'SEND_EMAIL_SCREEN',
  ENTER_PHONE_NUMBER_SCREEN: 'ENTER_PHONE_NUMBER_SCREEN',
  UPDATE_PROFILE_SCREEN: 'UPDATE_PROFILE_SCREEN',
  PASSWORD_SCREEN: 'PASSWORD_SCREEN',

  // LIST
  FOOD_LIST_SCREEN: 'FOOD_LIST_SCREEN',
  COURSE_LIST_SCREEN: 'COURSE_LIST_SCREEN',
  PRODUCT_LIST_SCREEN: 'PRODUCT_LIST_SCREEN',

  // FEATURE INFO
  YOUR_FAVORITE_SCREEN: 'YOUR_FAVORITE_SCREEN',
  PAYMENT_SCREEN: 'PAYMENT_SCREEN',
  PROMOTION_SCREEN: 'PROMOTION_SCREEN',
  ORDER_SCREEN: 'ORDER_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',

  // NAVIGATION SETTING
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PIN_CODE: 'CHANGE_PIN_CODE',

  // DETAILS
  DETAILS_COURSE_SCREEN: 'DETAILS_COURSE_SCREEN',
  FOOD_DETAILS_SCREEN: 'FOOD_DETAILS_SCREEN',
  ORDER_DETAIL_SCREEN: 'ORDER_DETAIL_SCREEN',
  PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',

  //Tabs
  TAB_DETAILS: 'TAB_DETAILS',
  TAB_LESSON: 'TAB_LESSON',

  // OTHER
  COURSE_LIST_TYPE_SCREEN: 'COURSE_LIST_TYPE_SCREEN',
  FILTER_SCREEN: 'FILTER_SCREEN',
  CART_SCREEN: 'CART_SCREEN',
};
