export const routes = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  HOMESCREEN: 'HOMESCREEN',
  SEND_EMAIL: 'SEND_EMAIL',
  VFTPHONENUMBERSCREEN: 'VFTPHONENUMBERSCREEN',
  BILLSCREEN: 'BILLSCREEN',
  PRODUCTSCREEN: 'PRODUCTSCREEN',
  CARTSCREEN: 'CARTSCREEN',
  INFOSCREEN: 'INFOSCREEN',
};
